/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

/**
 * External dependencies
 */
const CopyWebpackPlugin = require( 'copy-webpack-plugin' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		'admin/settings': path.resolve(
			process.cwd(),
			'src/admin/settings',
			'index.scss'
		),
		'experiments/example-experiment': path.resolve(
			process.cwd(),
			'src/experiments/example-experiment',
			'index.tsx'
		),
		'experiments/title-generation': path.resolve(
			process.cwd(),
			'src/experiments/title-generation',
			'index.tsx'
		),
		'experiments/ai-playground': path.resolve(
			process.cwd(),
			'src/experiments/ai-playground',
			'index.tsx'
		),
	},

	plugins: [
		// Include WP's plugin config.
		...defaultConfig.plugins,

		// Copy build styles from external packages.
		new CopyWebpackPlugin( {
			patterns: [
				{
					from: path.resolve(
						__dirname,
						'node_modules/wp-admin-components/build-style'
					),
					to: path.resolve(
						__dirname,
						'build/external/wp-admin-components'
					),
				},
				{
					from: path.resolve(
						__dirname,
						'node_modules/wp-interface/build-style'
					),
					to: path.resolve(
						__dirname,
						'build/external/wp-interface'
					),
				},
			],
		} ),

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
