/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
// eslint-disable-next-line import/no-extraneous-dependencies
const DependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );
const {
	defaultRequestToExternal,
	defaultRequestToHandle,
	// eslint-disable-next-line import/no-extraneous-dependencies
} = require( '@wordpress/dependency-extraction-webpack-plugin/lib/util' );

/**
 * External dependencies
 */
// eslint-disable-next-line import/no-extraneous-dependencies
const CopyWebpackPlugin = require( 'copy-webpack-plugin' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

/**
 * Packages that should be bundled rather than externalized because they
 * are not registered as WP script handles in all supported versions.
 */
const BUNDLED_PACKAGES = new Set( [ '@wordpress/dataviews', '@wordpress/ui' ] );

/**
 * Replace the default DependencyExtractionWebpackPlugin with one that
 * bundles the packages listed above instead of externalizing them.
 */
const plugins = defaultConfig.plugins.map( ( plugin ) => {
	if ( plugin.constructor.name !== 'DependencyExtractionWebpackPlugin' ) {
		return plugin;
	}

	return new DependencyExtractionWebpackPlugin( {
		requestToExternal( request ) {
			if ( BUNDLED_PACKAGES.has( request ) ) {
				// Return false (not undefined) to prevent the default
				// handler from externalizing the package.
				return false;
			}
			return defaultRequestToExternal( request );
		},
		requestToHandle( request ) {
			if ( BUNDLED_PACKAGES.has( request ) ) {
				return false;
			}
			return defaultRequestToHandle( request );
		},
	} );
} );

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	output: {
		...defaultConfig.output,
		path: path.resolve( process.cwd(), 'build-scripts' ),
	},
	entry: {
		...defaultConfig.entry(),
		'admin/settings': path.resolve(
			process.cwd(),
			'src/admin/settings',
			'index.scss'
		),
		'admin/ai-request-logs': path.resolve(
			process.cwd(),
			'src/admin/ai-request-logs',
			'index.tsx'
		),
		'admin/dashboard': path.resolve(
			process.cwd(),
			'src/admin/dashboard',
			'index.scss'
		),
		'experiments/content-classification': path.resolve(
			process.cwd(),
			'src/experiments/content-classification',
			'index.tsx'
		),
		'experiments/abilities-explorer': path.resolve(
			process.cwd(),
			'src/experiments/abilities-explorer',
			'index.js'
		),
		'experiments/example-experiment': path.resolve(
			process.cwd(),
			'src/experiments/example-experiment',
			'index.tsx'
		),
		'experiments/excerpt-generation': path.resolve(
			process.cwd(),
			'src/experiments/excerpt-generation',
			'index.tsx'
		),
		'features/image-generation': path.resolve(
			process.cwd(),
			'src/features/image-generation',
			'index.ts'
		),
		'experiments/meta-description': path.resolve(
			process.cwd(),
			'src/experiments/meta-description',
			'index.tsx'
		),
		'experiments/review-notes': path.resolve(
			process.cwd(),
			'src/experiments/review-notes',
			'index.tsx'
		),
		'experiments/refine-notes': path.resolve(
			process.cwd(),
			'src/experiments/refine-notes',
			'index.tsx'
		),
		'experiments/summarization': path.resolve(
			process.cwd(),
			'src/experiments/summarization',
			'index.tsx'
		),
		'experiments/title-generation': path.resolve(
			process.cwd(),
			'src/experiments/title-generation',
			'index.tsx'
		),
		'experiments/alt-text-generation': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'index.tsx'
		),
		'experiments/alt-text-generation-media': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'media.ts'
		),
		'experiments/alt-text-generation-bulk': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'bulk.ts'
		),
	},

	plugins: [
		...plugins,

		// Copy DataViews CSS into build/ so the plugin can enqueue it
		// on WP versions where wp-dataviews is not a registered style.
		new CopyWebpackPlugin( {
			patterns: [
				{
					from: path.resolve(
						__dirname,
						'node_modules/@wordpress/dataviews/build-style/style.css'
					),
					to: path.resolve( __dirname, 'build/admin/dataviews.css' ),
				},
			],
		} ),

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
