/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

/**
 * External dependencies
 */
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		'admin/settings': path.resolve(
			process.cwd(),
			'src/admin/settings',
			'index.scss'
		),
		'admin/mcp-server': path.resolve(
			process.cwd(),
			'src/admin/mcp-server',
			'index.tsx'
		),
		'admin/ai-request-logs': path.resolve(
			process.cwd(),
			'src/admin/ai-request-logs',
			'index.tsx'
		),
		'experiments/example-experiment': path.resolve(
			process.cwd(),
			'src/experiments/example-experiment',
			'index.tsx'
		),
		'experiments/title-generation': path.resolve(
			process.cwd(),
			'src/experiments/title-generation',
			'index.tsx'
		),
		'experiments/post-table-bulk': path.resolve(
			process.cwd(),
			'src/experiments/post-table-bulk',
			'index.tsx'
		),
		'experiments/type-ahead': path.resolve(
			process.cwd(),
			'src/experiments/type-ahead',
			'index.tsx'
		),
		'experiments/alt-text-generation': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'index.tsx'
		),
		'experiments/alt-text-generation-media': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'media.ts'
		),
		'experiments/comment-moderation': path.resolve(
			process.cwd(),
			'src/experiments/comment-moderation',
			'index.tsx'
		),
	},

	plugins: [
		// Include WP's plugin config.
		...defaultConfig.plugins,

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
