<?php
/**
 * Base64 encoded audio import WordPress Ability implementation.
 *
 * @package WordPress\AI
 */

declare( strict_types=1 );

namespace WordPress\AI\Abilities\Speech;

use Throwable;
use WP_Error;
use WordPress\AI\Abstracts\Abstract_Ability;
use WordPress\AiClient\Files\DTO\File;

/**
 * Base64 encoded audio import WordPress Ability.
 *
 * Imports base64-encoded audio into the media library, optionally attaching
 * it to a post.
 *
 * @since x.x.x
 */
class Import_Base64_Audio extends Abstract_Ability {

	/**
	 * {@inheritDoc}
	 *
	 * @since x.x.x
	 */
	protected function input_schema(): array {
		return array(
			'type'       => 'object',
			'properties' => array(
				'data'         => array(
					'type'              => 'string',
					'sanitize_callback' => 'sanitize_text_field',
					'description'       => esc_html__( 'The base64 encoded audio data to import into the media library.', 'ai' ),
				),
				'filename'     => array(
					'type'              => 'string',
					'sanitize_callback' => 'sanitize_text_field',
					'description'       => esc_html__( 'The filename of the audio, without extension.', 'ai' ),
				),
				'title'        => array(
					'type'              => 'string',
					'sanitize_callback' => 'sanitize_text_field',
					'description'       => esc_html__( 'The title of the audio attachment.', 'ai' ),
				),
				'description'  => array(
					'type'              => 'string',
					'sanitize_callback' => 'sanitize_text_field',
					'description'       => esc_html__( 'The description of the audio attachment.', 'ai' ),
				),
				'mime_type'    => array(
					'type'              => 'string',
					'sanitize_callback' => 'sanitize_text_field',
					'description'       => esc_html__( 'The MIME type of the audio.', 'ai' ),
				),
				'post_id'      => array(
					'type'              => 'integer',
					'sanitize_callback' => 'absint',
					'description'       => esc_html__( 'Optional post ID to attach the audio to.', 'ai' ),
				),
				'ai_generated' => array(
					'type'              => 'boolean',
					'sanitize_callback' => 'rest_sanitize_boolean',
					'description'       => esc_html__( 'Whether the audio was generated by AI.', 'ai' ),
				),
			),
			'required'   => array( 'data' ),
		);
	}

	/**
	 * {@inheritDoc}
	 *
	 * @since x.x.x
	 */
	protected function output_schema(): array {
		return array(
			'type'       => 'object',
			'properties' => array(
				'audio' => array(
					'type'        => 'object',
					'description' => esc_html__( 'Imported audio data.', 'ai' ),
					'properties'  => array(
						'id'       => array(
							'type'        => 'integer',
							'description' => esc_html__( 'Attachment ID.', 'ai' ),
						),
						'url'      => array(
							'type'        => 'string',
							'description' => esc_html__( 'Attachment URL.', 'ai' ),
						),
						'filename' => array(
							'type'        => 'string',
							'description' => esc_html__( 'Attachment filename.', 'ai' ),
						),
						'title'    => array(
							'type'        => 'string',
							'description' => esc_html__( 'Attachment title.', 'ai' ),
						),
					),
				),
			),
		);
	}

	/**
	 * {@inheritDoc}
	 *
	 * @since x.x.x
	 */
	protected function execute_callback( $input ) {
		$args = wp_parse_args(
			$input,
			array(
				'filename'     => 'ai-generated-audio-' . time(),
				'title'        => '',
				'description'  => '',
				'mime_type'    => null,
				'post_id'      => 0,
				'ai_generated' => false,
			),
		);

		// Verify the data is a base64 encoded string.
		try {
			$file = new File( $input['data'], $args['mime_type'] );
		} catch ( Throwable $t ) {
			return new WP_Error(
				'invalid_data',
				esc_html__( 'The data is not a valid base64 encoded string.', 'ai' )
			);
		}

		// Verify the data is valid audio.
		if ( ! $file->isAudio() ) {
			return new WP_Error(
				'invalid_data',
				esc_html__( 'The data is not valid audio.', 'ai' )
			);
		}

		$base64_data = $file->getBase64Data();

		if ( empty( $base64_data ) ) {
			return new WP_Error(
				'no_base64_data',
				esc_html__( 'No base64 data found in the provided input.', 'ai' )
			);
		}

		$result = $this->import_audio(
			$base64_data,
			array(
				'mime_type'    => $file->getMimeType(),
				'title'        => $args['title'],
				'description'  => $args['description'],
				'filename'     => $args['filename'],
				'post_id'      => absint( $args['post_id'] ),
				'ai_generated' => rest_sanitize_boolean( (bool) $args['ai_generated'] ),
			)
		);

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return array(
			'audio' => $result,
		);
	}

	/**
	 * {@inheritDoc}
	 *
	 * @since x.x.x
	 */
	protected function permission_callback( $args ) {
		if ( ! current_user_can( 'upload_files' ) ) {
			return new WP_Error(
				'insufficient_capabilities',
				esc_html__( 'You do not have permission to import audio.', 'ai' )
			);
		}

		$post_id = isset( $args['post_id'] ) ? absint( $args['post_id'] ) : 0;

		if ( $post_id && ! current_user_can( 'edit_post', $post_id ) ) {
			return new WP_Error(
				'insufficient_capabilities',
				esc_html__( 'You do not have permission to attach audio to this post.', 'ai' )
			);
		}

		return true;
	}

	/**
	 * {@inheritDoc}
	 *
	 * @since x.x.x
	 */
	protected function meta(): array {
		return array(
			'show_in_rest' => true,
		);
	}

	/**
	 * Imports audio from a base64 encoded string into the media library.
	 *
	 * @since x.x.x
	 *
	 * @param string               $data The base64 encoded audio data.
	 * @param array<string, mixed> $args The arguments for the audio import.
	 *                                   - mime_type: The MIME type of the audio (e.g., 'audio/mpeg').
	 *                                   - title: The title of the attachment.
	 *                                   - description: The description of the attachment.
	 *                                   - filename: The filename, without extension.
	 *                                   - post_id: Optional post ID to attach the audio to.
	 *                                   - ai_generated: Whether the audio was generated by AI.
	 * @return array<string, mixed>|\WP_Error The attachment data, or a WP_Error if there was an error.
	 */
	protected function import_audio( string $data, array $args = array() ) {
		require_once ABSPATH . 'wp-admin/includes/file.php';
		require_once ABSPATH . 'wp-admin/includes/media.php';
		require_once ABSPATH . 'wp-admin/includes/image.php';

		$decoded_data = base64_decode( $data, true );

		if ( false === $decoded_data ) {
			return new WP_Error(
				'invalid_base64',
				esc_html__( 'Failed to decode base64 audio data.', 'ai' )
			);
		}

		$temp_file = wp_tempnam( 'ai-audio' );

		$bytes_written = file_put_contents( $temp_file, $decoded_data ); // phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.file_ops_file_put_contents

		if ( false === $bytes_written ) {
			wp_delete_file( $temp_file );
			return new WP_Error(
				'write_failed',
				esc_html__( 'Failed to write audio data to temporary file.', 'ai' )
			);
		}

		$extension = wp_get_default_extension_for_mime_type( $args['mime_type'] );

		if ( ! $extension ) {
			$extension = 'mp3';
		}

		/**
		 * Filters the base filename (without extension) used when importing
		 * AI-generated audio.
		 *
		 * The returned value is sanitized via `sanitize_file_name()` and the
		 * extension is appended afterwards.
		 *
		 * @since x.x.x
		 *
		 * @param string               $filename The base filename, without extension.
		 * @param array<string, mixed> $args     The import arguments.
		 * @return string The filtered base filename, without extension.
		 */
		$filename = (string) apply_filters( 'wpai_generated_audio_filename', $args['filename'], $args );

		$file_array = array(
			'name'     => sanitize_file_name( $filename ) . '.' . $extension,
			'type'     => $args['mime_type'],
			'tmp_name' => $temp_file,
		);

		$post_data = array(
			'post_title'     => sanitize_text_field( $args['title'] ),
			'post_content'   => sanitize_text_field( $args['description'] ),
			'post_mime_type' => $args['mime_type'],
		);

		if ( $args['ai_generated'] ) {
			$post_data['meta_input'] = array(
				'wpai_generated' => 1,
			);
		}

		$attachment_id = media_handle_sideload( $file_array, (int) $args['post_id'], $args['description'], $post_data );

		if ( file_exists( $temp_file ) ) {
			wp_delete_file( $temp_file );
		}

		if ( is_wp_error( $attachment_id ) ) {
			return $attachment_id;
		}

		$attachment = get_post( $attachment_id );

		if ( ! $attachment ) {
			return new WP_Error(
				'attachment_not_found',
				esc_html__( 'Failed to retrieve attachment data.', 'ai' )
			);
		}

		$attached_file = get_attached_file( $attachment_id );

		return array(
			'id'       => $attachment_id,
			'url'      => wp_get_attachment_url( $attachment_id ),
			'filename' => $attached_file ? basename( $attached_file ) : '',
			'title'    => $attachment->post_title,
		);
	}
}
