<?php
/**
 * Handles asset enqueuing for the settings page.
 *
 * @package WordPress\AI
 */

namespace WordPress\AI\Admin;

/**
 * Manages scripts and styles for the admin settings page.
 *
 * @since 0.1.0
 */
class Settings_Page_Assets {
	private const SCRIPT_FILE = 'build/index.js';

	private const STYLE_FILE = 'build/style-index.css';

	private const STYLE_FILE_PATH = __DIR__ . '/../../build/style-index.css';

	/**
	 * Script handle for the settings page.
	 */
	public const SCRIPT_HANDLE = 'wp-ai-admin-settings';

	/**
	 * Style handle for the settings page.
	 */
	public const STYLE_HANDLE = 'wp-ai-admin-settings';

	/**
	 * Payload builder.
	 *
	 * @var \WordPress\AI\Admin\Settings_Payload_Builder
	 */
	private $payload_builder;

	/**
	 * Hook suffix for the settings page.
	 *
	 * @var string
	 */
	private $hook_suffix;

	/**
	 * Constructor.
	 *
	 * @since 0.1.0
	 *
	 * @param \WordPress\AI\Admin\Settings_Payload_Builder $payload_builder Payload builder.
	 */
	public function __construct( Settings_Payload_Builder $payload_builder ) {
		$this->payload_builder = $payload_builder;
	}

	/**
	 * Sets the hook suffix for conditional enqueueing.
	 *
	 * @since 0.1.0
	 *
	 * @param string $hook_suffix Hook suffix from add_options_page().
	 */
	public function set_hook_suffix( string $hook_suffix ): void {
		$this->hook_suffix = $hook_suffix;
	}

	/**
	 * Enqueues assets when the settings page is loaded.
	 *
	 * @since 0.1.0
	 *
	 * @param string $current_hook Current admin page hook.
	 */
	public function enqueue_assets( string $current_hook ): void {
		if ( $current_hook !== $this->hook_suffix ) {
			return;
		}

		$asset = $this->load_asset_metadata();

		if ( null !== $asset ) {
			wp_enqueue_script(
				self::SCRIPT_HANDLE,
				AI_PLUGIN_URL . self::SCRIPT_FILE,
				$asset['dependencies'],
				$asset['version'],
				true
			);

			// Inject settings payload for React hydration.
			wp_add_inline_script(
				self::SCRIPT_HANDLE,
				sprintf(
					'window.wpAiExperimentsSettings = %s;',
					wp_json_encode( $this->payload_builder->build() )
				),
				'before'
			);

			if ( file_exists( self::STYLE_FILE_PATH ) ) {
				wp_enqueue_style(
					self::STYLE_HANDLE,
					AI_PLUGIN_URL . self::STYLE_FILE,
					array( 'wp-components' ),
					$asset['version']
				);
			}
		} else {
			// Ensure core components styles are present for fallback markup.
			wp_enqueue_style( 'wp-components' );
		}
	}

	/**
	 * Loads the asset manifest generated by the build step.
	 *
	 * @since 0.1.0
	 *
	 * @return array<string, mixed>|null Asset metadata when available.
	 */
	private function load_asset_metadata(): ?array {
		if ( ! file_exists( __DIR__ . '/../../build/index.asset.php' ) ) {
			return null;
		}

		$asset = include __DIR__ . '/../../build/index.asset.php';

		return is_array( $asset ) ? $asset : null;
	}
}
