/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';

/**
 * Internal dependencies
 */
import { generateAltText } from '../../../utils/generate-alt-text';
import { runAbility } from '../../../utils/run-ability';
import { trimText } from '../../../utils/text';
import type {
	GeneratedImageData,
	ImageImportAbilityInput,
	ImageProgressCallback,
	UploadedImage,
} from '../types';

const { aiImageGenerationData } = window as any;

/**
 * Uploads an image to the media library.
 *
 * @param {GeneratedImageData} imageData               The generated image data (from generateImage).
 * @param {Object}             options                 Optional settings.
 * @param {Function}           options.onProgress      Callback invoked with progress messages.
 * @param {boolean}            options.altTextEnabled  Whether to generate alt text before upload.
 * @param {string}             options.filenameContext Context used to build a default filename.
 * @return {Promise<UploadedImage>} A promise that resolves to the uploaded image data.
 */
export async function uploadImage(
	{ image, prompt, prompts }: GeneratedImageData,
	options?: {
		onProgress?: ImageProgressCallback;
		altTextEnabled?: boolean;
		filenameContext?: string;
	}
): Promise< UploadedImage > {
	const onProgress = options?.onProgress;
	const promptHistory = prompts?.length ? prompts : [ prompt ];

	const params: ImageImportAbilityInput = {
		data: image.data,
		mime_type: 'image/png',
		description: sprintf(
			/* translators: 1: Provider name, 2: Model name, 3: Date, 4: Prompt */
			__( 'Generated by %1$s using %2$s on %3$s. Prompt: %4$s', 'ai' ),
			image.provider_metadata.name,
			image.model_metadata.name,
			new Date().toLocaleDateString(),
			promptHistory.join( ' | ' )
		),
		meta: [
			{
				key: 'ai_generated',
				value: '1',
			},
		],
	};

	// Use the prompt as alt text by default.
	params.alt_text = prompt;

	// If alt text generation is enabled, try generating alt text.
	const isAltTextEnabled =
		options?.altTextEnabled ?? aiImageGenerationData?.altTextEnabled;
	if ( isAltTextEnabled ) {
		try {
			onProgress?.( __( 'Generating alt text…', 'ai' ) );
			const altResult = await generateAltText(
				undefined,
				`data:image/png;base64,${ image.data }`
			);
			params.alt_text = altResult.alt_text;
		} catch {
			params.alt_text = prompt;
		}
	}

	// Set our image title to be a trimmed version of the alt text.
	params.title = trimText( params.alt_text ?? '' );

	if ( options?.filenameContext?.trim() ) {
		params.filename_context = options.filenameContext.trim();
	}

	onProgress?.( __( 'Importing image…', 'ai' ) );

	return await runAbility( 'ai/image-import', params )
		.then( ( response: any ) => {
			if (
				response &&
				typeof response === 'object' &&
				'image' in response
			) {
				return response.image as UploadedImage;
			}

			throw new Error( 'Invalid response from image import' );
		} )
		.catch( ( error ) => {
			throw new Error( error.message );
		} );
}
